(() => {
'use strict';
const K={pool:'op_pool_v6',fav:'op_fav_v6',del:'op_del_v6',seen:'op_seen_v6',hist:'op_hist_v6'};
const $=id=>document.getElementById(id), load=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const norm=s=>String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase();
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
const idFor=s=>'f-'+hash(norm(s)), pick=a=>a[Math.floor(Math.random()*a.length)], shuffle=a=>{for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let pool=load(K.pool),fav=load(K.fav),del=load(K.del),seen=load(K.seen),hist=load(K.hist),current=null,index=0,tab='history',freshIds=new Set();

const starts=['שאלה בלי הכנה מוקדמת:','במקום עוד היי רגיל:','נלך ישר למעניין:','מסקרן אותי לדעת:','שאלה קצת אחרת:','בלי תשובה נכונה או לא נכונה:','שאלה אקראית אבל טובה:','יש לי אחת מסקרנת:','בוא נתחיל ממשהו פחות צפוי:','שאלה של שתי שניות:','בא לי להתחיל דווקא מזה:','משהו קטן שמסקרן אותי:','בוא נוותר על הסמול טוק:','שאלה שאפשר לקחת לכל כיוון:','אחת לא צפויה:'];
const topics=[
['קליל','מה הדבר הקטן שהכי שיפר לך את השבוע?'],['קליל','איזה מקום תמיד עושה לך טוב?'],['קליל','מה תמיד מצליח להרים לך את מצב הרוח?'],['קליל','מה הדבר הראשון שהיית עושה ביום פנוי לגמרי?'],['קליל','איזה מאכל תמיד מנצח כשאין כוח להחליט?'],['קליל','מה היה הפלייליסט המושלם ליום הזה?'],['קליל','איזה ריח ישר מזכיר לך משהו טוב?'],['קליל','איזו שעה ביום הכי כיפית מבחינתך?'],
['מסקרן','מה הדבר האחרון שלמדת רק כי הסתקרנת?'],['מסקרן','איזה נושא יכול לגרום לך לשכוח מהשעה?'],['מסקרן','איזו החלטה ספונטנית יצאה לך הכי מוצלחת?'],['מסקרן','אם אפשר היה ללמוד משהו חדש בשנייה — מה היית בוחר?'],['מסקרן','מה הדבר הכי מפתיע שגילית לאחרונה?'],['מסקרן','איזו אפליקציה היית מוחק מהעולם ליום אחד?'],['מסקרן','איזה מקום היית רוצה לראות פעם אחת במציאות?'],['מסקרן','איזו המצאה קטנה חסרה לדעתך בעולם?'],
['עמוק','מה הופך מבחינתך שיחה רגילה לשיחה שבאמת זוכרים?'],['עמוק','איזה הרגל קטן עשה אצלך שינוי גדול?'],['עמוק','מה לדעתך אנשים מעריכים פחות ממה שמגיע לו?'],['עמוק','מה הופך יום רגיל ליום מוצלח?'],['עמוק','איזו תכונה אתה הכי מעריך באנשים?'],['עמוק','מה משהו שהיום חשוב לך יותר מפעם?'],['עמוק','איזו עצה טובה באמת נשארה איתך?'],['עמוק','מה לדעתך שווה להשקיע בו יותר זמן?'],
['מצחיק','איזה כישרון לא שימושי שלך דווקא די מרשים?'],['מצחיק','איזה חוק מצחיק היית מוסיף ליום אחד?'],['מצחיק','איזה מאכל כולם אוהבים ואתה פשוט לא מבין למה?'],['מצחיק','אם הטלפון שלך היה יכול להתלונן עליך — על מה זה היה?'],['מצחיק','איזה שם מצחיק היית נותן לסרט על השבוע שלך?'],['מצחיק','איזו קנייה קטנה הייתה הכי מיותרת אבל עדיין שווה?']
];
const tails=['',' תשובה ראשונה שעולה לך.',' בלי לחשוב יותר מדי.',' אפשר גם תשובה מפתיעה.',' ואם צריך לבחור רק אחד?',' מה הסיפור מאחורי זה?',' דווקא הפרטים הקטנים מעניינים.'];
const bridges=['','ואם כבר מדברים על זה — ','שאלה המשך: ','ועוד אחת באותו כיוון: '];
function add(item,fresh=false){const text=String(item.text||'').replace(/\s+/g,' ').trim();if(text.length<8||pool.some(x=>norm(x.text)===norm(text)))return false;const o={id:idFor(text),category:item.category||'מסקרן',text,source:item.source||'FREE',createdAt:new Date().toISOString()};pool.unshift(o);if(fresh)freshIds.add(o.id);return true}
function generate(count=60){let n=0,t=0;while(n<count&&t<count*40){t++;const [cat,core]=pick(topics);const mode=Math.random();let text=mode<.28?core:mode<.88?`${pick(starts)} ${core}${pick(tails)}`:`${pick(bridges)}${core}${pick(tails)}`;if(add({category:cat,text,source:'FREE'},true))n++}addMoments();pool=pool.slice(0,5000);save(K.pool,pool);return n}
function addMoments(){const d=new Date(),h=d.getHours(),day=d.getDay(),month=d.getMonth()+1;const moment=h<11?'מה יכול להפוך את הבוקר הזה למוצלח?':h<17?'אם הייתה לך עכשיו שעה פנויה לגמרי, מה היית עושה?':'מה היה החלק הכי טוב ביום שלך עד עכשיו?';add({category:'רגעי',text:`שאלה לפי הרגע: ${moment}`,source:'רגעי'},true);if(day===5||day===6)add({category:'רגעי',text:'סוף שבוע הגיע — מה מבחינתך הופך אותו למוצלח באמת?',source:'רגעי'},true);if(month>=6&&month<=9)add({category:'רגעי',text:'אם היית יכול לברוח עכשיו לכמה שעות של קיץ — לאן היית נוסע?',source:'רגעי'},true)}
function filtered(){const q=norm($('search').value),c=$('category').value;return pool.filter(x=>!del.includes(x.id)&&(c==='all'||x.category===c)&&(!q||norm(x.text).includes(q))).sort((a,b)=>(seen.includes(a.id)?1:0)-(seen.includes(b.id)?1:0))}
function setCurrent(x,list){current=x;if(!x){$('opener').textContent='אין תוצאות';$('position').textContent='0 מתוך 0';return}index=Math.max(0,list.findIndex(i=>i.id===x.id));$('opener').textContent=x.text;$('catLabel').textContent=x.category;$('position').textContent=`${index+1} מתוך ${list.length}`;$('source').textContent=x.source==='רגעי'?'מותאם לרגע':'נוצר במנוע FREE';$('freshBadge').style.display=freshIds.has(x.id)?'inline-block':'none';$('favBtn').classList.toggle('active',fav.includes(x.id));if(!seen.includes(x.id)){seen.unshift(x.id);seen=seen.slice(0,5000);save(K.seen,seen)}hist=hist.filter(id=>id!==x.id);hist.unshift(x.id);hist=hist.slice(0,100);save(K.hist,hist);stats()}
function render(){const list=filtered();if(current&&list.some(x=>x.id===current.id))setCurrent(current,list);else setCurrent(list[0]||null,list);$('freshCount').textContent=`${freshIds.size} חדשים`;$('syncState').textContent='FREE · עובד מקומית · ללא API';stats();renderPanel()}
function move(step){const list=filtered();if(!list.length)return;let i=current?list.findIndex(x=>x.id===current.id):-1;i=(i+step+list.length)%list.length;setCurrent(list[i],list)}
function stats(){$('totalStat').textContent=filtered().length;$('favStat').textContent=fav.length;$('deletedStat').textContent=del.length;$('seenStat').textContent=seen.length}
function byId(id){return pool.find(x=>x.id===id)}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderPanel(){let ids=tab==='favorites'?fav:tab==='deleted'?del:hist;const rows=ids.map(byId).filter(Boolean).slice(0,40);$('panel').innerHTML=rows.length?rows.map(x=>`<div class="row"><div class="rowtext">${escapeHtml(x.text)}</div><button class="mini" data-open="${x.id}">פתח</button>${tab==='deleted'?`<button class="mini" data-restore="${x.id}">שחזר</button>`:''}</div>`).join(''):'<div class="empty">אין כאן פריטים עדיין</div>'}
function favToggle(){if(!current)return;fav=fav.includes(current.id)?fav.filter(x=>x!==current.id):[current.id,...fav];save(K.fav,fav);render()}
function removeCurrent(){if(!current)return;del=[current.id,...del.filter(x=>x!==current.id)];save(K.del,del);current=null;render()}
function restore(id){del=del.filter(x=>x!==id);save(K.del,del);render()}
async function copyCurrent(){if(!current)return;try{await navigator.clipboard.writeText(current.text);$('copyBtn').textContent='הועתק';setTimeout(()=>$('copyBtn').textContent='העתק',900)}catch{}}
function context(){const h=new Date().getHours();$('contextLine').textContent=`${h<11?'בוקר':h<17?'צהריים':'ערב'} · מנוע FREE חכם`}
$('nextBtn').onclick=()=>move(1);$('prevBtn').onclick=()=>move(-1);$('copyBtn').onclick=copyCurrent;$('favBtn').onclick=favToggle;$('deleteBtn').onclick=removeCurrent;
$('moreBtn').onclick=()=>{const n=generate(60);$('syncState').textContent=`נוצרו עכשיו ${n} פתיחות חדשות · ללא API`;current=null;render()};
$('category').onchange=()=>{current=null;render()};$('search').oninput=()=>{current=null;render()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;renderPanel()});
$('panel').onclick=e=>{const o=e.target.dataset.open,r=e.target.dataset.restore;if(r)return restore(r);if(o){const x=byId(o);if(x){current=x;render();window.scrollTo({top:0,behavior:'smooth'})}}};
if(!pool.length)topics.forEach(([category,text])=>add({category,text,source:'FREE'}));context();generate(80);shuffle(pool);save(K.pool,pool);render();
})();